# Puerto donde corre la aplicacion
server.port=8080

# Configuracion de la base de datos H2
# mem:ecommercedb significa que la base de datos vive en memoria RAM
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

# Habilitar la consola visual de H2
# Se puede acceder en: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA
# create-drop: crea las tablas al iniciar y las borra al apagar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
